@ColetaAPI_HostAddress = https://localhost:7116

### GET ALL DATABASE DATA (LOCATIONS + COLLECTIONS)
GET {{ColetaAPI_HostAddress}}/api/Database/GetAll
Accept: application/json

###

POST {{ColetaAPI_HostAddress}}/api/Location/Add
Content-Type: application/json

{
  "description": "Umbrella Street"
}

GET {{ColetaAPI_HostAddress}}/api/Location/GetAll
Accept: application/json

GET {{ColetaAPI_HostAddress}}/api/Location/GetById/1
Accept: application/json

PUT {{ColetaAPI_HostAddress}}/api/Location/Update
Content-Type: application/json

{
  "id": 1,
  "description": "Umbrella Avenue"
}

DELETE {{ColetaAPI_HostAddress}}/api/Location/Delete/1
Accept: application/json

POST {{ColetaAPI_HostAddress}}/api/Collection/Add
Content-Type: application/json

{
  "locationId": 1,
  "orderDate": "2025-10-26T10:30:00",
  "collected": false
}

GET {{ColetaAPI_HostAddress}}/api/Collection/GetAll
Accept: application/json

GET {{ColetaAPI_HostAddress}}/api/Collection/GetSingle/1
Accept: application/json

PUT {{ColetaAPI_HostAddress}}/api/Collection/Update
Content-Type: application/json

{
  "id": 1,
  "locationId": 1,
  "orderDate": "2025-10-26T10:30:00",
  "collected": true
}

DELETE {{ColetaAPI_HostAddress}}/api/Collection/Delete/1
Accept: application/json
